smartoffice/smartoffices/smartoffices/urls.py
from django.contrib import admin
from django.urls import path

from jefe import views as jefeViews
from trabajador import views as trabajador
from usuario import views as usuario

urlpatterns = [
    path('admin/', admin.site.urls),
    # usuario inicio
    path('',usuario.home, name='home'),
    # Jefe
    path('jefe/', jefeViews.home, name='jefeHome'),
    path('user/signupJefe/',usuario.crearJefe, name='signupJefe' ),
    path('jefe/signin/', jefeViews.signin, name='jefeSignin'),
    path('jefe/signout/', jefeViews.signout, name='jefeSignout'),
    path('jefe/edit/', jefeViews.editarPerfil, name='jefeEditarPerfil'),
    # Jefe - Equipos
    path('jefe/newTeam/', jefeViews.crearEquipo, name='jefeCrearEquipo'),
    path('jefe/teams/', jefeViews.listarEquipos, name='jefeListarEquipos'),
    path('jefe/teams/<int:equipo_id>', jefeViews.editarEquipo, name='jefeEditarEquipo'),
    path('jefe/teams/<int:equipo_id>/ver', jefeViews.verEquipo, name='jefeVerEquipo'),
    path('jefe/teams/<int:equipo_id>/delete', jefeViews.eliminarEquipo, name='jefeEliminarEquipo'),
    path('jefe/teams/asignar/', jefeViews.asignarAEquipo, name='jefeAsignarAEquipo'),
    
    path('jefe/teams/tarea/', jefeViews.asignarTareaAEquipo, name='jefeAsignarTareaAEquipo'),
    path('jefe/teams/tarea/<int:equipo_id>', jefeViews.crearTarea, name='jefeCrearTarea'),
    path('jefe/teams/tarea/<int:equipo_id>/ver', jefeViews.verTareas, name='jefeVerTareas'),

    path('jefe/teams/reunion/', jefeViews.asignarReunionAEquipo, name='jefeAsignarReunionAEquipo'),
    path('jefe/teams/reunion/<int:equipo_id>', jefeViews.crearReunion, name='jefeCrearReunion'),
    path('jefe/teams/reunion/<int:equipo_id>/retroalimentacion/<int:reunion_id>', jefeViews.agregarRetroalimentacion, name='jefeAgregarRetroalimentacion'),
    path('jefe/teams/reunion/<int:equipo_id>/ver', jefeViews.verReuniones, name='jefeVerReuniones'),
    # Jefe - Trabajadores
    path('user/signupTrabajador/',usuario.crearTrabajador, name='signupTrabajador' ),
    path('jefe/trabajadores/',jefeViews.listarTrabajadores, name='listarTrabajadores' ),
    path('jefe/trabajadores/<int:trabajador_id>', jefeViews.editarTrabajador, name='editarTrabajador'),
    path('jefe/trabajadores/<int:trabajador_id>/delete', jefeViews.eliminarTrabajador, name='eliminarTrabajador'),
    path('jefe/trabajadores/<int:trabajador_id>/estados', jefeViews.estadosTrabajador, name='estadosTrabajador'),

    # Trabajador
    path('trabajador/', trabajador.home, name='trabajadorHome'),
    path('trabajador/signin/', trabajador.signin, name='trabajadorSignin'),
    path('trabajador/signout/', trabajador.signout, name='trabajadorSignout'),
    path('trabajador/edit/', trabajador.editarPerfil, name='trabajadorEditarPerfil'),

    # Trabajador tareas
    path('trabajador/tareas', trabajador.tareas, name='trabajadorTareas'),
    path('trabajador/tareas/<int:tarea_id>', trabajador.marcarTareaCompletada, name='trabajadorMacarTareaCompletada'),

    # Trabajador reuniones
    path('trabajador/reuniones', trabajador.reuniones, name='trabajadorReuniones'),
    path('trabajador/reuniones/<int:reunion_id>', trabajador.reunionRetroalimentacion, name='trabajadorReunionRetroalimentacion'),
]

smartoffice/smartoffices/usuario/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from django.conf import settings

# Create your models here.
class UsuarioManager(BaseUserManager):
  def create_usuario(self, username, email, nombre, apellidos, password = None, jefe = False ):
    if not email:
      raise ValueError('El usuario debe tener un correo')
    usuario = self.model(
      username = username,
      email = self.normalize_email(email),
      nombre = nombre,
      apellidos = apellidos,
      jefe = jefe
    )
    usuario.set_password(password)
    usuario.save()
    return usuario
  def create_superuser(self, username, email, nombre, apellidos, password):
    usuario = self.create_usuario(username, email, nombre, apellidos, password)
    usuario.administrador = True
    usuario.save()
    return usuario

class Usuario(AbstractBaseUser):
  username = models.CharField('Username',unique=True, max_length=100)
  email = models.EmailField('Correo electrónico',unique=True, max_length=100)
  nombre = models.CharField('Nombre', max_length=100, blank=False)
  apellidos = models.CharField('Apellidos', max_length=200, blank=False)
  administrador = models.BooleanField(default=False)
  jefe = models.BooleanField(default=False)
  objects = UsuarioManager()

  USERNAME_FIELD = 'username'
  REQUIRED_FIELDS = ['email','nombre','apellidos']

  def __str__(self):
    return f'Usuario {self.username}'
  def has_perm(self,perm,obj=None):
    return True
  def has_module_perms(self,app_label):
    return True
  
  @property
  def is_staff(self):
    return self.administrador

smartoffice/smartoffices/jefe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Equipo, EquipoHasTrabajador, Tarea, Reunion
from usuario import models as UsuarioModel

class JefeCreationForm(UserCreationForm):
  correo = forms.EmailField()
  nombre = forms.CharField()
  apellidos = forms.CharField()

  class Meta:
    model = User
    fields = ['username','nombre','correo','apellidos','password1','password2']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].help_text = None
    self.fields['password1'].help_text = None
    self.fields['password2'].help_text = None

class JefeUpdateForm(forms.ModelForm):
  correo = forms.EmailField()
  nombre = forms.CharField()
  apellidos = forms.CharField()

  class Meta:
    model = User
    fields = ['username','nombre','correo','apellidos']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].help_text = None

class EquipoForm(forms.ModelForm):
  class Meta:
    model = Equipo
    fields = ['titulo', 'descripcion']

class TrabajadorForm(forms.ModelForm):
  class Meta:
    model = UsuarioModel.Usuario
    fields = ['username','email','nombre','apellidos']

class AsignarEquipoForm(forms.ModelForm):
  class Meta:
    model = EquipoHasTrabajador
    fields = ['equipo','trabajador']

class TareaForm(forms.ModelForm):
  class Meta:
    model = Tarea
    fields = ['trabajador','titulo','descripcion']

class ReunionForm(forms.ModelForm):
  class Meta:
    model = Reunion
    fields = ['titulo','link','descripcion','fecha']

smartoffice/smartoffices/usuario/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.db import IntegrityError

from .models import Usuario

# Create your views here.
def home(request):
  return render(request, 'index.html')

def crearJefe(request):
  if request.method == 'GET':
    return render(request,'signupJefe.html')
  else:
    if request.POST['password1'] == request.POST['password2']:
      try:
        jefeUser = Usuario.objects.create_usuario(
          username=request.POST['username'],
          email=request.POST['correo'],
          nombre=request.POST['nombre'],
          apellidos=request.POST['apellidos'],
          jefe=True,
          password=request.POST['password1']
        )
        jefeUser.save()
        login(request, jefeUser)
        return redirect('jefeHome')
      except IntegrityError:
        return render(request,'signupJefe.html',{
          'error':'El usuario ya existe.'
        })
    return render(request,'signupJefe.html',{
      'error':'Las contraseñas no coinciden.'
    })

def crearTrabajador(request):
  if request.method == 'GET':
    return render(request,'signupTrabajador.html')
  else:
    if request.POST['password1'] == request.POST['password2']:
      try:
        trabajadorUser = Usuario.objects.create_usuario(
          username=request.POST['username'],
          email=request.POST['correo'],
          nombre=request.POST['nombre'],
          apellidos=request.POST['apellidos'],
          password=request.POST['password1'],
        )
        trabajadorUser.save()
        return render(request, 'signupTrabajador.html', {'success': 'Trabajador creado correctamente.'});
      except IntegrityError:
        return render(request,'signupTrabajador.html',{
          'error':'El trabajador ya existe.'
        })
    return render(request,'signupTrabajador.html',{
      'error':'Las contraseñas no coinciden.'
    })

smartoffice/smartoffices/usuario/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />

  <title>SmartOffices - Inicio</title>
</head>
<body>
  <div class="container vh-100 w-100 d-flex flex-column justify-content-center align-items-center">
    <h1 class="mb-3">SmartOffices</h1>
    <div class="w-25 d-flex flex-column gap-3">
      <a href="/jefe/signin" class="btn btn-primary btn-block">Jefe</a>
      <a href="/trabajador/signin" class="btn btn-primary btn-block">Trabajador</a>
    </div>
  </div>
</body>

smartoffice/smartoffices/usuario/templates/signupJefe.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-25 mt-5">
  <h1>Crear cuenta de jefe</h1>
  {% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
  {% endif %}
  <form action="/user/signupJefe/" method="post">
    {% csrf_token %}
    <!-- Email input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="id_username">Username:</label>
      <input name="username" type="text" id="id_username" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_nombre">Nombre:</label>
      <input name="nombre" type="text" id="id_nombre" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_apellidos">Apellidos:</label>
      <input name="apellidos" type="text" id="id_apellidos" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_correo">Correo:</label>
      <input name="correo" type="email" id="id_correo" class="form-control" autofocus required/>
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="id_password1">Contraseña:</label>
      <input type="password" id="id_password1" class="form-control" name="password1" required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_password2">Repetir contraseña:</label>
      <input type="password" id="id_password2" class="form-control" name="password2" required/>
    </div>
  
    <!-- Submit button -->
    <div class="d-flex flex-row justify-content-between">
      <button class="btn btn-primary btn-block mb-4">Crear cuenta</button>
      <a href="/jefe/signin/" class="btn btn-link btn-block mb-4">Iniciar sesión</a>
    </div>
  </form>
</div>
{% endblock %}

smartoffice/smartoffices/usuario/templates/signupTrabajador.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50 mt-5">
  <h1>Crear cuenta de trabajador</h1>
  {% if success %}
  <div class="alert alert-success" role="alert">
    {{ success }}
  </div>
  {% endif %}
  {% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
  {% endif %}
  <form action="/user/signupTrabajador/" method="post">
    {% csrf_token %}
    <!-- Email input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="id_username">Username:</label>
      <input name="username" type="text" id="id_username" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_nombre">Nombre:</label>
      <input name="nombre" type="text" id="id_nombre" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_apellidos">Apellidos:</label>
      <input name="apellidos" type="text" id="id_apellidos" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_correo">Correo:</label>
      <input name="correo" type="email" id="id_correo" class="form-control" autofocus required/>
    </div>
  
    <!-- Password input -->
    <div class="form-outline mb-4">
      <label class="form-label" for="id_password1">Contraseña:</label>
      <input type="password" id="id_password1" class="form-control" name="password1" required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_password2">Repetir contraseña:</label>
      <input type="password" id="id_password2" class="form-control" name="password2" required/>
    </div>
  
    <!-- Submit button -->
    <div class="d-grid">
      <button class="btn btn-primary btn-block mb-4">Crear cuenta</button>
    </div>
  </form>
</div>
{% endblock %}