smartoffice/smartoffices/smartoffices/urls.py
from django.contrib import admin
from django.urls import path

from jefe import views as jefeViews
from trabajador import views as trabajador
from usuario import views as usuario

urlpatterns = [
    path('admin/', admin.site.urls),
    # usuario inicio
    path('',usuario.home, name='home'),
    # Jefe
    path('jefe/', jefeViews.home, name='jefeHome'),
    path('user/signupJefe/',usuario.crearJefe, name='signupJefe' ),
    path('jefe/signin/', jefeViews.signin, name='jefeSignin'),
    path('jefe/signout/', jefeViews.signout, name='jefeSignout'),
    path('jefe/edit/', jefeViews.editarPerfil, name='jefeEditarPerfil'),
    # Jefe - Equipos
    path('jefe/newTeam/', jefeViews.crearEquipo, name='jefeCrearEquipo'),
    path('jefe/teams/', jefeViews.listarEquipos, name='jefeListarEquipos'),
    path('jefe/teams/<int:equipo_id>', jefeViews.editarEquipo, name='jefeEditarEquipo'),
    path('jefe/teams/<int:equipo_id>/ver', jefeViews.verEquipo, name='jefeVerEquipo'),
    path('jefe/teams/<int:equipo_id>/delete', jefeViews.eliminarEquipo, name='jefeEliminarEquipo'),
    path('jefe/teams/asignar/', jefeViews.asignarAEquipo, name='jefeAsignarAEquipo'),
    
    path('jefe/teams/tarea/', jefeViews.asignarTareaAEquipo, name='jefeAsignarTareaAEquipo'),
    path('jefe/teams/tarea/<int:equipo_id>', jefeViews.crearTarea, name='jefeCrearTarea'),
    path('jefe/teams/tarea/<int:equipo_id>/ver', jefeViews.verTareas, name='jefeVerTareas'),

    path('jefe/teams/reunion/', jefeViews.asignarReunionAEquipo, name='jefeAsignarReunionAEquipo'),
    path('jefe/teams/reunion/<int:equipo_id>', jefeViews.crearReunion, name='jefeCrearReunion'),
    path('jefe/teams/reunion/<int:equipo_id>/retroalimentacion/<int:reunion_id>', jefeViews.agregarRetroalimentacion, name='jefeAgregarRetroalimentacion'),
    path('jefe/teams/reunion/<int:equipo_id>/ver', jefeViews.verReuniones, name='jefeVerReuniones'),
    # Jefe - Trabajadores
    path('user/signupTrabajador/',usuario.crearTrabajador, name='signupTrabajador' ),
    path('jefe/trabajadores/',jefeViews.listarTrabajadores, name='listarTrabajadores' ),
    path('jefe/trabajadores/<int:trabajador_id>', jefeViews.editarTrabajador, name='editarTrabajador'),
    path('jefe/trabajadores/<int:trabajador_id>/delete', jefeViews.eliminarTrabajador, name='eliminarTrabajador'),
    path('jefe/trabajadores/<int:trabajador_id>/estados', jefeViews.estadosTrabajador, name='estadosTrabajador'),

    # Trabajador
    path('trabajador/', trabajador.home, name='trabajadorHome'),
    path('trabajador/signin/', trabajador.signin, name='trabajadorSignin'),
    path('trabajador/signout/', trabajador.signout, name='trabajadorSignout'),
    path('trabajador/edit/', trabajador.editarPerfil, name='trabajadorEditarPerfil'),

    # Trabajador tareas
    path('trabajador/tareas', trabajador.tareas, name='trabajadorTareas'),
    path('trabajador/tareas/<int:tarea_id>', trabajador.marcarTareaCompletada, name='trabajadorMacarTareaCompletada'),

    # Trabajador reuniones
    path('trabajador/reuniones', trabajador.reuniones, name='trabajadorReuniones'),
    path('trabajador/reuniones/<int:reunion_id>', trabajador.reunionRetroalimentacion, name='trabajadorReunionRetroalimentacion'),
]

smartoffice/smartoffices/jefe/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from django.conf import settings


from usuario import models as usuarioModels

# Create your models here.

class TranslateTexts(models.Model):
    TYPE_LANGUAGE_CHOICES = [("en","English"), ("fr","Francais"), ("de", "Deutch"), ("zh-Hans","Chinesse")]
    language_code_origin = models.CharField(max_length=2)
    language_code_destiny = models.CharField(max_length=7, choices= TYPE_LANGUAGE_CHOICES)
    text_to_translate = models.CharField(max_length=255)
    text_translated = models.CharField(max_length=255)


class Equipo(models.Model):
  titulo = models.CharField(max_length=200)
  descripcion = models.TextField(max_length=1000)
  jefe = models.ForeignKey(usuarioModels.Usuario, on_delete=models.CASCADE)

  def __str__(self):
    return self.titulo + ' - ' + self.jefe.username

class EquipoHasTrabajador(models.Model):
  equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
  trabajador = models.OneToOneField(usuarioModels.Usuario, on_delete=models.CASCADE)
  def __str__(self):
    return self.equipo.titulo + ' - ' + self.trabajador.username

class Tarea(models.Model):
  equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
  trabajador = models.ForeignKey(usuarioModels.Usuario, on_delete=models.CASCADE)
  titulo = models.CharField(max_length=200)
  descripcion = models.TextField(max_length=1000)
  completado = models.BooleanField(default=False)
  def __str__(self):
    return self.equipo.titulo + ' - ' + self.titulo

class Reunion(models.Model):
  equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
  titulo = models.CharField(max_length=200)
  link = models.CharField(max_length=200)
  descripcion = models.TextField(max_length=1000)
  fecha = models.CharField(max_length=50)
  retroalimentacion = models.TextField(max_length=1000, default="")
  def __str__(self):
    return self.equipo.titulo + ' - ' + self.titulo

smartoffice/smartoffices/jefe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Equipo, EquipoHasTrabajador, Tarea, Reunion
from usuario import models as UsuarioModel

class JefeCreationForm(UserCreationForm):
  correo = forms.EmailField()
  nombre = forms.CharField()
  apellidos = forms.CharField()

  class Meta:
    model = User
    fields = ['username','nombre','correo','apellidos','password1','password2']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].help_text = None
    self.fields['password1'].help_text = None
    self.fields['password2'].help_text = None

class JefeUpdateForm(forms.ModelForm):
  correo = forms.EmailField()
  nombre = forms.CharField()
  apellidos = forms.CharField()

  class Meta:
    model = User
    fields = ['username','nombre','correo','apellidos']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].help_text = None

class EquipoForm(forms.ModelForm):
  class Meta:
    model = Equipo
    fields = ['titulo', 'descripcion']

class TrabajadorForm(forms.ModelForm):
  class Meta:
    model = UsuarioModel.Usuario
    fields = ['username','email','nombre','apellidos']

class AsignarEquipoForm(forms.ModelForm):
  class Meta:
    model = EquipoHasTrabajador
    fields = ['equipo','trabajador']

class TareaForm(forms.ModelForm):
  class Meta:
    model = Tarea
    fields = ['trabajador','titulo','descripcion']

class ReunionForm(forms.ModelForm):
  class Meta:
    model = Reunion
    fields = ['titulo','link','descripcion','fecha']

smartoffice/smartoffices/jefe/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

from .forms import JefeUpdateForm, EquipoForm, TrabajadorForm, AsignarEquipoForm, TareaForm, ReunionForm
from .models import Equipo, EquipoHasTrabajador, Tarea, Reunion
from usuario import models as usuarioModels
from trabajador.models import EstadoAnimo

# Create your views here.
@login_required
def home(request):
  return render(request,'home.html')

@login_required
def signout(request):
  logout(request)
  return redirect('jefeSignin')

def signin(request):
  if request.method == 'GET':
    return render(request, 'signin.html');
  else:
    user = authenticate(request, username=request.POST['username'], password=request.POST['password1'])
    if user is None:
        return render(request, 'signin.html', {"error": "El username o la contraseña son incorrectos."})
    login(request, user)
    return redirect('jefeHome')

# Perfil
@login_required
def editarPerfil(request):
  if request.method == 'GET':
    return render(request, 'editarPerfil.html');
  else:
    form = JefeUpdateForm(data=request.POST, instance=request.user)
    if form.is_valid():
      form.save()
      return render(request, 'editarPerfil.html', {'success': 'Datos actualizados correctamente.'});
    else:
      return render(request, 'editarPerfil.html', {'error':'Los datos ingresados no son válidos.'});

# Equipo
@login_required
def crearEquipo(request):
  if request.method == "GET":
    return render(request, 'equipo/crearEquipo.html');
  else:
    try:
      form = EquipoForm(request.POST)
      new_equipo = form.save(commit=False)
      new_equipo.jefe = request.user
      new_equipo.save()
      return render(request, 'equipo/crearEquipo.html', {"success": "Equipo creado correctamente."}) 
    except ValueError:
      return render(request, 'equipo/crearEquipo.html', {"error": "Error creando equipo."}) 

@login_required
def listarEquipos(request):
  equipos = Equipo.objects.filter(jefe=request.user)
  return render(request, 'equipo/equipos.html', {"equipos": equipos})

@login_required
def editarEquipo(request, equipo_id):
  if request.method == 'GET':
    equipo = get_object_or_404(Equipo, pk=equipo_id, jefe=request.user)
    form = EquipoForm(instance=equipo)
    return render(request, 'equipo/editarEquipo.html', {'equipo': equipo})
  else:
    try:
      equipo = get_object_or_404(Equipo, pk=equipo_id, jefe=request.user)
      form = EquipoForm(data=request.POST, instance=equipo)
      if form.is_valid():
        form.save()
        return render(request, 'equipo/editarEquipo.html', {"success": "Equipo editado correctamente.",'equipo': equipo}) 
      else:
        return render(request, 'equipo/editarEquipo.html', {"error": "No se pudo editar el equipo.",'equipo': equipo}) 
    except ValueError:
      return render(request, 'equipo/editarEquipo.html', {"error": "No se pudo editar el equipo.",'equipo': equipo}) 

@login_required
def eliminarEquipo(request, equipo_id):
  equipo = get_object_or_404(Equipo, pk=equipo_id, jefe=request.user)
  if request.method == 'POST':
    equipo.delete()
    return redirect('jefeListarEquipos')

@login_required
def verEquipo(request, equipo_id):
  equipo = get_object_or_404(Equipo, pk=equipo_id, jefe=request.user)
  equipos = EquipoHasTrabajador.objects.select_related().filter(equipo=equipo_id)
  return render(request, 'equipo/equipo.html', {"equipos": equipos, 'equipo':equipo})

# Trabajadores
@login_required
def listarTrabajadores(request):
  trabajadores = usuarioModels.Usuario.objects.filter(jefe=False);
  return render(request, 'trabajador/trabajadores.html', {"trabajadores": trabajadores})

@login_required
def editarTrabajador(request, trabajador_id):
  if request.method == 'GET':
    trabajador = get_object_or_404(usuarioModels.Usuario, pk=trabajador_id)
    return render(request, 'trabajador/editarTrabajador.html', {'trabajador': trabajador})
  else:
    try:
      trabajador = get_object_or_404(usuarioModels.Usuario, pk=trabajador_id)
      form = TrabajadorForm(data=request.POST, instance=trabajador)
      if form.is_valid():
        form.save()
        return render(request, 'trabajador/editarTrabajador.html', {"success": "Trabajador editado correctamente.",'trabajador': trabajador}) 
      else:
        return render(request, 'trabajador/editarTrabajador.html', {"error": "No se pudo editar el trabajador.",'trabajador': trabajador}) 
    except ValueError:
      return render(request, 'trabajador/editarTrabajador.html', {"error": "No se pudo editar el trabajador.",'trabajador': trabajador}) 

@login_required
def eliminarTrabajador(request, trabajador_id):
  trabajador = get_object_or_404(usuarioModels.Usuario, pk=trabajador_id)
  if request.method == 'POST':
    trabajador.delete()
    return redirect('listarTrabajadores')

@login_required
def estadosTrabajador(request, trabajador_id):
  trabajador = get_object_or_404(usuarioModels.Usuario, pk=trabajador_id)
  estados = EstadoAnimo.objects.filter(usuario=trabajador)
  return render(request, 'trabajador/estadosAnimo.html',{'trabajador':trabajador,'estados':estados})

@login_required
def asignarAEquipo(request):
  if request.method == 'GET':
    equipos = Equipo.objects.filter(jefe=request.user)
    trabajadores = usuarioModels.Usuario.objects.filter(jefe=False);
    return render(request,'equipo/asignarAEquipo.html', {'equipos':equipos, 'trabajadores':trabajadores})
  else:
    try:
      equipos = Equipo.objects.filter(jefe=request.user)
      trabajadores = usuarioModels.Usuario.objects.filter(jefe=False);
      form = AsignarEquipoForm(request.POST)
      new_equipo = form.save(commit=False)
      new_equipo.save()
      return render(request,'equipo/asignarAEquipo.html', {'equipos':equipos, 'trabajadores':trabajadores, 'success':'Se agrego el trabajador al equipo correctamente.'})
    except ValueError:
      return render(request,'equipo/asignarAEquipo.html', {'equipos':equipos, 'trabajadores':trabajadores, 'error':'No se pudo agregar el trabajador al equipo.'})

# Tareas
@login_required
def asignarTareaAEquipo(request):
  equipos = Equipo.objects.filter(jefe=request.user)
  return render(request, 'tarea/asignarTarea.html', {"equipos": equipos})
@login_required
def crearTarea(request, equipo_id):
  if request.method == "GET":
    trabajadores = EquipoHasTrabajador.objects.select_related().filter(equipo=equipo_id)
    return render(request, 'tarea/crearTarea.html',{'trabajadores':trabajadores, 'equipo_id':equipo_id});
  else:
    try:
      trabajadores = EquipoHasTrabajador.objects.select_related().filter(equipo=equipo_id)
      form = TareaForm(request.POST)
      nuevaTarea = form.save(commit=False)
      nuevaTarea.equipo = get_object_or_404(Equipo, pk=equipo_id)
      nuevaTarea.save()
      return render(request, 'tarea/crearTarea.html',{'trabajadores':trabajadores, 'equipo_id':equipo_id, 'success':'Tarea asignada correctamente.'});
    except ValueError as e:
      print(e)
      return render(request, 'tarea/crearTarea.html',{'trabajadores':trabajadores, 'equipo_id':equipo_id, 'error':'Error al asignar tarea.'});
@login_required
def verTareas(request, equipo_id):
  tareas = Tarea.objects.select_related().filter(equipo=equipo_id)
  return render(request, 'tarea/tareas.html', {"tareas": tareas})

# Reunion
@login_required
def asignarReunionAEquipo(request):
  equipos = Equipo.objects.filter(jefe=request.user)
  return render(request, 'reunion/asignarReunion.html', {"equipos": equipos})

@login_required
def crearReunion(request, equipo_id):
  if request.method == "GET":
    return render(request, 'reunion/crearReunion.html',{'equipo_id':equipo_id});
  else:
    try: 
      form = ReunionForm(request.POST)
      nuevaReunion = form.save(commit=False)
      nuevaReunion.equipo = get_object_or_404(Equipo, pk=equipo_id)
      nuevaReunion.retroalimentacion = ""
      nuevaReunion.save()
      return render(request, 'reunion/crearReunion.html',{'equipo_id':equipo_id, 'success': 'Reunión creada correctamente.'})
    except ValueError as e:
        print(e)
        return render(request, 'reunion/crearReunion.html',{'equipo_id':equipo_id, 'error': 'Error al crear una reunión.'})

@login_required
def verReuniones(request, equipo_id):
  reuniones = Reunion.objects.select_related().filter(equipo=equipo_id)
  return render(request, 'reunion/reuniones.html', {"reuniones": reuniones, "equipo_id":equipo_id})

@login_required
def agregarRetroalimentacion(request,equipo_id,reunion_id):
  if request.method == "GET":
    return render(request, 'reunion/agregarRetroalimentacion.html',{'equipo_id':equipo_id,'reunion_id':reunion_id})
  else:
    try:
      reunion = get_object_or_404(Reunion, pk=reunion_id)
      reunion.retroalimentacion = request.POST['retroalimentacion']
      reunion.save()
      return redirect('jefeAsignarReunionAEquipo')
    except ValueError:
      return render(request, 'reunion/agregarRetroalimentacion.html',{'equipo_id':equipo_id,'reunion_id':reunion_id, 'error': 'Error al agregar retroalimentación.'})

smartoffice/smartoffices/jefe/templates/reunion/agregarRetroalimentacion.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50 mt-5">
  <h1>Agregar retroalimentación</h1>
  {% if success %}
  <div class="alert alert-success" role="alert">
    {{ success }}
  </div>
  {% endif %}
  {% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
  {% endif %}
  <form action="/jefe/teams/reunion/{{equipo_id}}/retroalimentacion/{{reunion_id}}" method="post">
    {% csrf_token %}
    <div class="form-outline mt-4 mb-4">
      <label class="form-label" for="id_retroalimentacion">Retroalimentación:</label>
      <textarea class="form-control" name="retroalimentacion" id="id_retroalimentacion" style="height: 100px" required></textarea>
    </div>
    <!-- Submit button -->
    <div class="d-grid">
      <button class="btn btn-primary mb-4">Agregar retroalimentación</button>
    </div>
  </form>
</div>
{% endblock %}

smartoffice/smartoffices/jefe/templates/reunion/asignarReunion.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5 d-flex flex-column align-items-center">
  <h1 class="align-self-start">Asignar reunión</h1>


  <table class="table w-75">
    <thead>
      <tr>
        <th scope="col">Equipo</th>
        <th scope="col">Ver reuniones</th>
        <th scope="col">Agregar reunión</th>
      </tr>
    </thead>
    {% for equipo in equipos %}
    <tbody>
      <tr>
        <td>{{equipo.titulo}}</td>
        <td>
          <a href="/jefe/teams/reunion/{{equipo.id}}/ver"><i class="fa-solid fa-eye"></i></a>
        </td>
        <td>
          <a href="/jefe/teams/reunion/{{equipo.id}}"><i class="fa-regular fa-pen-to-square"></i></a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock %}

smartoffice/smartoffices/jefe/templates/reunion/crearReunion.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50 mt-5">
  <h1>Crear reunión</h1>
  {% if success %}
  <div class="alert alert-success" role="alert">
    {{ success }}
  </div>
  {% endif %}
  {% if error %}
  <div class="alert alert-danger" role="alert">
    {{error}}
  </div>
  {% endif %}
  <form action="/jefe/teams/reunion/{{ equipo_id }}" method="post">
    {% csrf_token %}
    <div class="form-outline mb-4">
      <label class="form-label" for="id_titulo">Titulo:</label>
      <input name="titulo" type="text" id="id_titulo" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_link">Link:</label>
      <input name="link" type="text" id="id_link" class="form-control" autofocus required/>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_descripcion">Descripción:</label>
      <textarea class="form-control" name="descripcion" id="id_descripcion" style="height: 100px" required></textarea>
    </div>
    <div class="form-outline mb-4">
      <label class="form-label" for="id_fecha">Fecha y hora:</label>
      <input name="fecha" type="datetime-local" id="id_fecha" class="form-control" autofocus required/>
    </div>
  
    <!-- Submit button -->
    <div class="d-grid">
      <button class="btn btn-primary mb-4">Crear reunión</button>
    </div>
  </form>
</div>
{% endblock %}

smartoffice/smartoffices/jefe/templates/reunion/reuniones.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <h1>Reuniones creadas</h1>


  <table class="table">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">URL</th>
        <th scope="col">Descripción</th>
        <th scope="col">Fecha</th>
        <th scope="col">Retroalimentación</th>
      </tr>
    </thead>
    {% for reunion in reuniones %}
    <tbody>
      <tr>
        <td>{{reunion.titulo}}</td>
        <td><a href="{{reunion.link}}">{{reunion.link}}</a></td>
        <td>{{reunion.descripcion}}</td>
        <td>{{reunion.fecha}}</td>
        <td>
          <a href="/jefe/teams/reunion/{{equipo_id}}/retroalimentacion/{{reunion.id}}">Añadir</i></a>
        </td>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock %}